image: node

stages:
  - build
  - test
  - deploy

.global_rules:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success

lint:
  # extends: .global_rules
  stage: .pre
  script: 
    - echo preliminary job
    # Install eslint
    - npm i eslint
    # Run eslint
    - node_modules/eslint/bin/eslint.js .

build:
  extends: .global_rules
  stage: build
  before_script:
    # Install WebPack
    - npm i webpack
  script:
    - echo building with webpack
    - npm run build
    # - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

